"""email Migration

Revision ID: 0748fca2c49e
Revises: eda47753e80e
Create Date: 2022-03-12 21:07:13.042745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0748fca2c49e'
down_revision = 'eda47753e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('fullname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'fullname')
    # ### end Alembic commands ###
