"""blog Migration

Revision ID: 36a8ea188f86
Revises: 7f54b9a5243d
Create Date: 2022-03-13 23:37:14.871603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a8ea188f86'
down_revision = '7f54b9a5243d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'postedby')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('postedby', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
