"""blog Migration

Revision ID: 7f54b9a5243d
Revises: fca70b3bd22a
Create Date: 2022-03-13 23:37:00.648230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f54b9a5243d'
down_revision = 'fca70b3bd22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('postedby', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'postedby')
    # ### end Alembic commands ###
