"""email Migration

Revision ID: ebc7a4e2410d
Revises: 0748fca2c49e
Create Date: 2022-03-12 21:34:23.842912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc7a4e2410d'
down_revision = '0748fca2c49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('postedby', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'postedby')
    # ### end Alembic commands ###
