"""email Migration

Revision ID: eda47753e80e
Revises: a012f53d660a
Create Date: 2022-03-12 19:13:10.986664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda47753e80e'
down_revision = 'a012f53d660a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'username')
    # ### end Alembic commands ###
