"""remove fifields Migration

Revision ID: f1691a59b38b
Revises: 42d45bca0cf9
Create Date: 2022-03-13 12:52:18.969667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1691a59b38b'
down_revision = '42d45bca0cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'postedby')
    op.drop_column('comments', 'madeby')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('madeby', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('postedby', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
